### ISSUE TITLE
Предложение заменить перевод "Бесплотный предмет" на "Эфемерный".

### ISSUE THREAD

**Issue by mmelnik** [AlexSnowLeo/D2R.Ru.Localization.Mod#5]
Привет авторам и спасибо за проделанную работу! От оригинальной локализации кровоточат глаза.

Хотел привлечь внимание к переводу слова "Ethereal" в официальной версии.

В локализации, "Бесплотный предмет" не является корректным переводом и не отражает истинного смысла слова "Ethereal" в контексте хрупкости предметов. Вместо этого прилагательное "Эфемерный" является более правильным и подходящим по смыслу так как отражает мнимость и недолговечность/скоротечность вещей, а также выглядит красивее и подходит по стилю.

Пример:
"Ethereal (Cannot be Repaired)" -> "Эфемерная вещь (нельзя отремонтировать)"
или
"Ethereal (Cannot be Repaired)" -> "Эфемерный предмет (нельзя отремонтировать)"

**Comment by AlexSnowLeo** [comment]
@mmelnik Добрый день. 
Спасибо за уточнение. Лично я согласен, что бесплотный не отражает сути, это все применяется по-отношению к предмету. "Эфемерный" - это как раз можно транслировать как "недолговечный", "временный".
Попробую спросить у автора перевода @Alk0zAuruS, если он одобрит - проведу правки.

**Comment by AlexSnowLeo** [comment]
de958460814c498cb52e0af46ad43d50959abe1c

**Comment by AlexSnowLeo** [comment]
Изменено в релизе https://github.com/AlexSnowLeo/D2R.Ru.Localization.Mod/releases/tag/2022-11-14
